[package]
name = "progress_string"
version = "0.1.1"
authors = ["FreeMasen"]
description = "Generate a progress bar string"
repository = "https://github.com/freemasen/progress_string"

[dependencies]
